version: "3.5"

services:
  flask_app:
    container_name: flask_app
    image: mohamedrafraf/flask-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=mohamed
      - DB_PASSWORD=postgres
      - DB_HOST=flask_db
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      - flask_db
    entrypoint: ./entrypoint.sh
    restart: always

  flask_db:
    container_name: flask_db
    image: postgres:12
    restart: always 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=mohamed
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
